# Generated by Django 3.2.5 on 2021-08-03 20:19

from django.db import migrations, models
import mytodolist_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodolist_app', '0002_auto_20210803_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to=mytodolist_app.models.upload_callable),
        ),
    ]
