# Generated by Django 3.2.5 on 2021-08-05 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytodolist_app', '0003_todo_attached_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'permissions': [('my_permission', 'Can do permission')]},
        ),
    ]
